In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report

In [11]:
df = pd.read_csv('loan_data.csv')
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [13]:
x = df.drop(columns=['loan_status'])
y = df['loan_status']

In [14]:
num_cols = x.select_dtypes(include='number').columns
x = x[num_cols]

In [15]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,train_size=0.8)

In [16]:
grid_search = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid={
           'criterion' : ['gini','entropy'],
           'splitter' : ['best','random'],
           'max_depth' : [None,5,10,20],
           'min_samples_split': [2,3,5,7],
           'min_samples_leaf' : [1,3,5,7],
           'max_features' : ['sqrt','log2']         
    },
    cv=3,
    verbose=1, # to get the information about fit we use verbose
    error_score='raise', #np.nan
    n_jobs=1 # it decides how many cpu cores to use. if -1 all cpu-cores and runs parallely.
)

grid_search.fit(xtrain,ytrain)

Fitting 3 folds for each of 512 candidates, totalling 1536 fits

GridSearchCV(cv=3, error_score='raise',
             estimator=DecisionTreeClassifier(random_state=42), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 3, 5, 7],
                         'min_samples_split': [2, 3, 5, 7],
                         'splitter': ['best', 'random']},
             verbose=1)

In [17]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'splitter': 'best'}

In [18]:
model = grid_search.best_estimator_
model.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=10, max_features='log2', min_samples_split=5,
                       random_state=42)

In [19]:
results = pd.DataFrame(grid_search.cv_results_)
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
164,0.061892,0.003987,0.005233,0.000556,gini,10,log2,1,5,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.855000,0.855333,0.849583,0.853306,0.002636,1
166,0.089530,0.024229,0.006044,0.001433,gini,10,log2,1,7,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.853583,0.853583,0.851750,0.852972,0.000864,2
162,0.071530,0.017094,0.009252,0.003916,gini,10,log2,1,3,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.849750,0.855000,0.851750,0.852167,0.002163,3
116,0.035358,0.005313,0.005341,0.001904,gini,5,log2,5,5,best,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.851333,0.854417,0.850667,0.852139,0.001633,4
118,0.056873,0.017165,0.012229,0.004045,gini,5,log2,5,7,best,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.851333,0.854417,0.850667,0.852139,0.001633,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,0.008662,0.000470,0.004336,0.000476,entropy,5,sqrt,3,3,random,"{'criterion': 'entropy', 'max_depth': 5, 'max_...",0.783083,0.785167,0.785250,0.784500,0.001002,504
329,0.008342,0.000450,0.004651,0.000954,entropy,5,sqrt,3,2,random,"{'criterion': 'entropy', 'max_depth': 5, 'max_...",0.783083,0.785167,0.785250,0.784500,0.001002,504
77,0.010646,0.000507,0.004350,0.000443,gini,5,sqrt,3,5,random,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.783083,0.785167,0.785250,0.784500,0.001002,504
79,0.009699,0.000914,0.003678,0.000460,gini,5,sqrt,3,7,random,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.783083,0.785167,0.785250,0.784500,0.001002,504
257,0.047315,0.009451,0.010997,0.004350,entropy,None,sqrt,1,2,random,"{'criterion': 'entropy', 'max_depth': None, 'm...",0.779500,0.778083,0.786917,0.781500,0.003874,512

In [20]:
ytrain_pred = model.predict(xtrain) # For CV = 3

print(classification_report(ytrain,ytrain_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92     28010
           1       0.77      0.64      0.70      7990

    accuracy                           0.88     36000
   macro avg       0.84      0.79      0.81     36000
weighted avg       0.87      0.88      0.87     36000

In [21]:
ytrain_pred = model.predict(xtrain) # For CV = 10

print(classification_report(ytrain,ytrain_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92     28010
           1       0.77      0.64      0.70      7990

    accuracy                           0.88     36000
   macro avg       0.84      0.79      0.81     36000
weighted avg       0.87      0.88      0.87     36000

In [22]:
import os

print(os.cpu_count()) #12 cpu scores

12