In [1]:
#pip install category_encoders

In [2]:
import pandas as pd
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split

## Target Encoder

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({'Name':['A','B','A','C','B','A','C','B','A','C'],
    'Product_type':['Electronics','Electronics','Furniture','Acessories','Furniture','Electronics','Accesories','Furniture','Electronics','Accesories'],
    'label':[1000,500,300,450,650,350,200,400,300,200]
})

In [5]:
x = df.drop(columns='label')
y = df['label']

In [6]:
xtrain,xtest,ytrain,ytest =train_test_split( 
    x,y,test_size=0.2,random_state=42
)

In [7]:
encoder = TargetEncoder(handle_unknown="value")
encoder.fit_transform(xtrain,ytrain)

         Name  Product_type
5  460.161934    476.553059
0  460.161934    476.553059
7  455.275399    444.715408
2  460.161934    444.715408
9  418.971197    409.173803
4  455.275399    444.715408
3  418.971197    444.563178
6  418.971197    409.173803

In [8]:
encoder.transform(xtest)

         Name  Product_type
8  460.161934    476.553059
1  455.275399    476.553059

## Scenario - 2

In [9]:
df1 = pd.DataFrame({'Name':['A','B','A','C','B','A','C','B','A','C'],
    'Product_type':['Electronics','Electronics','Furniture','Acessories','Furniture','Electronics','Accesories','Furniture','Electronics','Accesories'],
    'label':[1000,500,300,450,650,350,200,400,300,200]
})

In [10]:
df1

  Name Product_type  label
0    A  Electronics   1000
1    B  Electronics    500
2    A    Furniture    300
3    C   Acessories    450
4    B    Furniture    650
5    A  Electronics    350
6    C   Accesories    200
7    B    Furniture    400
8    A  Electronics    300
9    C   Accesories    200

In [11]:
x = df1.drop(columns='label')
y = df1['label']

In [12]:
xtrain,xtest,ytrain,ytest =train_test_split( 
    x,y,test_size=0.2,random_state=42
)

In [13]:
encoder = TargetEncoder(handle_unknown="value")
encoder.fit_transform(xtrain,ytrain)

         Name  Product_type
5  460.161934    476.553059
0  460.161934    476.553059
7  455.275399    444.715408
2  460.161934    444.715408
9  418.971197    409.173803
4  455.275399    444.715408
3  418.971197    444.563178
6  418.971197    409.173803